name: Distribute NuGet Package

on:
  release:
    types: [ published ]

defaults:
  run:
    shell: pwsh

jobs:

  distribute_nuget:
    name: Distribute NuGet Package
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.0
      - name: Add NuGet to PATH
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_TOKEN }}
      - name: Build NuGet
        run: msbuild ./Library/Library.sln /r /p:Configuration=Release /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:PackageOutputPath="${{ github.workspace }}/output" /t:Pack
      - name: Push to NuGet
        run: nuget push output\*.nupkg -Source https://api.nuget.org/v3/index.json