name: Distribute NuGet Package

on:
  release:
    types: [ published ]

defaults:
  run:
    shell: pwsh

jobs:

  distribute_nuget:
    name: Distribute NuGet Package
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.0
      - name: Build NuGet
        run: msbuild ./Library/Library.sln /r /p:Configuration=Release /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:PackageOutputPath="${{ github.workspace }}/output" /t:Pack
      - name: Push to GitHub Packages
        if: ${{ github.event_name == 'push' && github.ref == 'master' }}
        run: |
          nuget sources add -name "GitHub" `
            -Source "https://nuget.pkg.github.com/mattleibow/XamarinGitHubActions/index.json" `
            -Username mattleibow `
            -Password ${{ secrets.GITHUB_TOKEN }}
          nuget push output\*.nupkg -Source "GitHub" -SkipDuplicate

