name: Build App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Build
        run: dotnet build -c Release
      - name: Publish
        run: dotnet publish -c Release -o output
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: App
          path: output
  run:
    name: Run App
    runs-on: windows-latest
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: App
      - name: Run
        run: dotnet XamarinGitHubActions.dll
