name: "Build Mobile App"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: pwsh

jobs:
  # Android
  build_android:
    name: Run Android App
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Xamarin
        uses: maxim-lobanov/setup-xamarin@v1.1
        with:
          xamarin-ios-version: latest
          xamarin-mac-version: latest
          xamarin-android-version: latest
          xcode-version: latest
      - name: Build App
        run: msbuild ./MobileApp/MobileApp.Android/MobileApp.Android.csproj /r /p:Configuration=Release /t:SignAndroidPackage
      - name: Copy Build Output
        run: |
          New-Item ./output -Type Directory -Force
          Copy-Item ./MobileApp/MobileApp.Android/bin/Release/*-Signed.aab ./output/
          Copy-Item ./MobileApp/MobileApp.Android/bin/Release/*.aab.mSYM ./output/ -Recurse -Force
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Android App
          path: output
